  config {
    type: "table",
    database: databases.stage,
    schema: "DATASET_PRUEBA",
    name: "TBL_AREAS_STG_PRUEBA",

    bigquery: {
      clusterBy: ["ar_area_id", "ar_venue_id"]
    },

    tags: ["prueba_areas_stg"],

    assertions: {
      uniqueKey: ["ar_area_id"]
    }
  }

  SELECT
    ar_area_id,
    ar_name,
    ar_smoking,
    ar_timestamp,
    ar_venue_id,
    ar_external_id,
    updated_at,
    CURRENT_TIMESTAMP() AS ingestion_ts

  FROM
    ${ref(
      databases.raw,
      "DATASET_PRUEBA",
      "TBL_AREAS_RAW_PRUEBA"
    )}