config {
  type: "operations",
  schema: "RAW_WIGOS_SANMARCOS",
  name: "TBL_DRAW_TICKETS_RAW",
  database: (databases.raw),
  hasOutput: true
}

CREATE TABLE IF NOT EXISTS ${databases.raw}.RAW_WIGOS_SANMARCOS.TBL_DRAW_TICKETS_RAW
(
  IdControlIntegraciones  INT64 NOT NULL,
  dt_id                   INT64 NOT NULL,
  dt_created              DATETIME NOT NULL,
  dt_draw_id              INT64 NOT NULL,
  dt_account_id           INT64 NOT NULL,
  dt_first_number         INT64 NOT NULL,
  dt_last_number          INT64 NOT NULL,
  dt_voucher_id           INT64,
  dt_per_points           BOOL NOT NULL,
  dt_awarded_day          DATETIME NOT NULL,
  dt_auto_print_status    INT64,
  updated_at              INT64
)
PARTITION BY DATE(dt_created)
CLUSTER BY dt_account_id, dt_draw_id;
