config {
  type: "table",
  database: databases.stage, 
  schema: "STG_WIGOS_NEWYORK",
  name: "TBL_GAMING_TABLES_TYPES_STG", 
  bigquery: {
    clusterBy: ["gtt_gaming_table_type_id", "gtt_report_type_id"],
  },
    tags: ["carga_full_diaria_stg_newyork"]

}

SELECT
  gtt_gaming_table_type_id,
  gtt_name,
  gtt_enabled,
  gtt_report_type_id,
  CURRENT_TIMESTAMP() AS ingestion_ts
FROM
  ${ref(databases.raw, "RAW_WIGOS_NEWYORK", "TBL_GAMING_TABLES_TYPES_RAW")}
