config {
  type: "operations",
  schema: "RAW_SIMPHONY",
  name: "TBL_GN_INTEGRA_MICROS_KDS_RAW",
  database: (databases.raw),
  hasOutput: true
}

CREATE TABLE IF NOT EXISTS ${databases.raw}.RAW_SIMPHONY.TBL_GN_INTEGRA_MICROS_KDS_RAW
(
  SalaNombre                    STRING,
  business_date                 DATETIME,
  rvc_num                       INT64,
  rvc_name                      STRING,
  emp_num                       INT64,
  emp_name1                     STRING,
  chk_seq                       INT64,
  chk_num                       INT64,
  chk_open_date_time            DATETIME,
  chk_clsd_date_time            DATETIME,
  start_date_tm                 DATETIME,
  end_date_tm                   DATETIME,
  prep_time                     INT64,
  tiempoPreparacion             TIME,
  D_dtl_seq                     INT64,
  D_dtl_PLU                     INT64,
  D_dtl_name                    STRING,
  rangoPreparacion              STRING NOT NULL,
  diaSemana                     STRING,
  diferencia_inicio_fin_comanda INT64
)

PARTITION BY DATE(business_date)
CLUSTER BY rvc_num, chk_num, business_date