config {
  type: "table",
  database: databases.stage,
  schema: "STG_WIGOS_TAJMAHAL",
  name: "TBL_GN_INTEGRA_ACTIVIDAD_DEALER_STG",
  partitionBy: "DATE(GTDS_STARTED)",
  clusterBy: ["GU_USER_ID", "GT_GAMING_TABLE_ID"],
  tags: ["carga_full_diaria_stg_tajmahal_lote2"]
}

SELECT
  GTDS_STARTED,
  GTDS_FINISHED,
  TIME,
  GU_USER_ID,
  GU_FULL_NAME,
  SUPERVISOR,
  GT_GAMING_TABLE_ID,
  GT_NAME,
  OCCUPANCY,
  PLAYS,
  DROP_AMOUNT,
  BILL_DROP,
  BUY_IN,
  CHIPS_IN,
  CHIPS_OUT,
  FILLS,
  CREDITS,
  GTDSC_ISO_CODE,
  CURRENT_TIMESTAMP() AS ingestion_ts
FROM
  ${ref(databases.raw, "RAW_WIGOS_TAJMAHAL", "TBL_GN_INTEGRA_ACTIVIDAD_DEALER_RAW")}