config {
  type: "operations",
  schema:  "RAW_INTERFACES",
  name: "TBL_VENTA_X_DIA_CENTRO_CONSUMO_RAW",
  database: (databases.raw),
  hasOutput: true
}

CREATE TABLE IF NOT EXISTS ${databases.raw}.RAW_INTERFACES.TBL_VENTA_X_DIA_CENTRO_CONSUMO_RAW
(
  
  D_SALA                        STRING,
  D_CENTRO_CONSUMO              STRING,
  F_FECHA                       DATETIME,
  M_VENTAS_NETAS                NUMERIC,
  CONTEO                        INT64
)
