config {
  type: "operations",
  schema: "RAW_INTERFACES",
  name: "TBL_CORTE_CAJA_SIMPHONY_RAW",
  database: (databases.raw),
  hasOutput: true
}

CREATE TABLE IF NOT EXISTS ${databases.raw}.RAW_INTERFACES.TBL_CORTE_CAJA_SIMPHONY_RAW
(
  FechaProceso   DATETIME NOT NULL,
  Sala           STRING NOT NULL,
  CentroConsumo  STRING NOT NULL,
  Forma_Pago     STRING NOT NULL,
  Monto          NUMERIC
)