config {
  type: "table",
  database: databases.stage,
  schema: "STG_INTERFACES",
  name: "TBL_VENTA_X_DIA_CENTRO_CONSUMO_STG",
  tags: ["carga_full_diaria_stg_interfaces"]
}

SELECT
  K_VENTA_X_DIA_CENTRO_CONSUMO,
  F_FECHA,
  D_LOCALIZACION,
  D_CENTRO_CONSUMO,
  M_VENTAS_NETAS,
  N_DESCUENTOS,
  N_SERVICE_CHARGE,
  N_IMPUESTOS,
  F_MODIFICACION,
  CURRENT_TIMESTAMP() AS ingestion_ts
FROM
  ${ref(databases.raw, "RAW_INTERFACES", "TBL_VENTA_X_DIA_CENTRO_CONSUMO_RAW")}
