config {
    type: "operations",
    schema: "DATASET_PRUEBA",
    name: "TBL_AREAS_RAW_PRUEBA",
    database: (databases.raw),
    hasOutput: true
}

CREATE TABLE IF NOT EXISTS ${databases.raw}.DATASET_PRUEBA.TBL_AREAS_RAW_PRUEBA
(
  ar_area_id      INT64     NOT NULL,
  ar_name         STRING    NOT NULL,
  ar_smoking      BOOL      NOT NULL,
  ar_timestamp    STRING    NOT NULL,
  ar_venue_id     INT64,
  ar_external_id  STRING,
  updated_at int64 
)

CLUSTER BY ar_area_id;