

config {
  type: "incremental",
  database: databases.golden, 
  schema: "GLD_REPORTE_TRANSITORIO",
  name: "TBL_PUNTOS_A_LA_FECHA_GLD",
  uniqueKey: ["Num_Cliente"], 
  bigquery: {
    clusterBy: ["Num_Cliente"]
  },
  tags: ["carga_incremental_diaria_bi"]
}

WITH puntos AS (
  SELECT 
    num_cliente,
    id_sala, 
    Sala,
    SUM(Puntos_Asignados_Maquinas) + SUM(Puntos_Asignados_Mesas) AS puntos_sum
  FROM ${ref("TBL_INDICADORES_LB_GLD")} 

  GROUP BY num_cliente, id_sala, Sala
),

puntos_ranking AS (
  SELECT 
    num_cliente,
    id_sala,
    Sala,
    puntos_sum,
    ROW_NUMBER() OVER(PARTITION BY num_cliente ORDER BY puntos_sum DESC) as ranking
  FROM puntos
), 
max_puntos as (
SELECT 
  num_cliente,
  id_sala,
  Sala,
  puntos_sum AS max_puntos
FROM puntos_ranking
WHERE ranking = 1

)

select a.Num_Cliente, Titular ,b.sala as Sala_Max,cast('0.0'as numeric) as Puntos_a_la_fecha ,Nivel as Nivel_Wigos 
 from ${ref("TBL_ACCOUNTS_CLIENTE_UNICO_GLD")}  A
join max_puntos b
on a.Num_Cliente=b.Num_Cliente