config {
  type: "table",
  database: databases.stage,
  schema: "STG_WIGOS_CONSTITUCION",
  name: "TBL_DRAW_TICKETS_STG",
  partitionBy: "DATE(dt_created)",
  clusterBy: ["dt_account_id", "dt_draw_id"],
  tags: ["carga_full_diaria_stg_constitucion_lote2"]
}

SELECT
  IdControlIntegraciones,
  dt_id,
  dt_created,
  dt_draw_id,
  dt_account_id,
  dt_first_number,
  dt_last_number,
  dt_voucher_id,
  dt_per_points,
  dt_awarded_day,
  dt_auto_print_status,
  updated_at,
  CURRENT_TIMESTAMP() AS ingestion_ts
FROM
  ${ref(databases.raw, "RAW_WIGOS_CONSTITUCION", "TBL_DRAW_TICKETS_RAW")}
