config {
  type: "view",
  database: databases.golden,
  schema: "GLD_ALIMENTOS_Y_BEBIDAS",
  name: "VW_GN_INTEGRA_MICROS_KDS_GLD"
}

SELECT
  SalaNombre,
  business_date,
  rvc_num,
  rvc_name,
  emp_num,
  emp_name1,
  chk_seq,
  chk_num,
  chk_open_date_time,
  chk_clsd_date_time,
  start_date_tm,
  end_date_tm,
  prep_time,
  tiempoPreparacion,
  D_dtl_seq,
  D_dtl_PLU,
  D_dtl_name,
  rangoPreparacion,
  diaSemana,
  diferencia_inicio_fin_comanda,
  CURRENT_TIMESTAMP() AS ingestion_ts
FROM
  ${ref("STG_SIMPHONY", "TBL_GN_INTEGRA_MICROS_KDS_STG")}