config {
  type: "incremental",
  database: databases.stage,
  schema: "STG_SIMPHONY",
  name: "TBL_INTER2_MICWIG_DETALLE_STG",
  uniqueKey: ["iNumDetalle"],
  clusterBy: ["iNumHeader", "acSitio"],
  tags: ["carga_incremental_diaria_stg_simphony"]
}

SELECT
  iNumDetalle,
  iNumHeader,
  acSitio,
  acTipoItem,
  iPLUCodigo,
  acNombreItem,
  iCantidadItem,
  dSubtotalD,
  dIvaD,
  dTotalD,
  iOtrosDescuentos,
  CURRENT_TIMESTAMP() AS ingestion_ts
FROM
  ${ref(databases.raw, "RAW_SIMPHONY", "TBL_INTER2_MICWIG_DETALLE_RAW")}