config {
  type: "table",
  database: databases.stage, 
  schema: "STG_WIGOS_PARADISEISLAND",
  name: "TBL_CUSTOMER_BUCKET_STG",
  bigquery: {
    clusterBy: ["cbu_customer_id"]
  },
 tags: ["carga_full_diaria_stg_paradiseisland"],
  assertions: {
    uniqueKey: ["cbu_customer_id", "cbu_bucket_id"] 
  }
}

SELECT
  cbu_customer_id,
  cbu_bucket_id,
  cbu_value,
  cbu_updated,
  cbu_timestamp,
  updated_at,
  CURRENT_TIMESTAMP() AS ingestion_ts
FROM
  ${ref(databases.raw, "RAW_WIGOS_PARADISEISLAND", "TBL_CUSTOMER_BUCKET_RAW")}
